name: event_digital
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  dynamic_height_grid_view: ^0.0.4
  intl: ^0.19.0
  extended_image: ^8.2.0
  sqflite: ^2.3.3+1
  # google_fonts: ^6.2.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Sathoshi
      fonts:
        - asset: fonts/Satoshi-Regular.ttf
        - asset: fonts/Satoshi-Bold.ttf

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
